# This file sources other files in `hyprland` and `custom` folders
# You wanna add your stuff in files in `custom`

$qsConfig = ii
exec = hyprctl dispatch submap global # DO NOT REMOVE THIS OR YOU WON'T BE ABLE TO USE ANY KEYBIND
submap = global # This is required for catchall to work

# Environment variables
source=hyprland/env.conf
source=custom/env.conf

# Defaults
source=hyprland/execs.conf
source=hyprland/general.conf
source=hyprland/rules.conf
source=hyprland/colors.conf
source=hyprland/keybinds.conf

# Custom
source=custom/execs.conf
source=custom/general.conf
source=custom/rules.conf
source=custom/keybinds.conf

# nwg-displays support
source=workspaces.conf
source=monitors.conf

exec-once = systemctl --user start hyprland-session.target
# exec-once = kanshi
exec-once = python3 .config/controller/controller.py

xwayland {
  force_zero_scaling = true
}

# When lid is CLOSED: Disable internal, move everything to Xiaomi
bindl=,switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"

# When lid is OPENED: Re-enable internal (BOE) at your specific 1.6 scale
bindl=,switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, 2560x1600@120, 0x0, 1.6"

exec-once = hyprctl output create headless
workspace = 30, monitor:HEADLESS-1, default:true

env = GDK_SCALE,2
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# Ensure Qt uses the Wayland backend (just in case)
env = QT_QPA_PLATFORM,wayland;xcb
